
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# View Resolver Setting
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
# files which need thymeleaf got to set path like /thymeleaf/main

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.c6i1ktrvha7p.us-west-1.rds.amazonaws.com:3306/innodb
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# SQL Command in the Console
#spring.jpa.show-sql=true

# ddl-auto : update schema with the given value


server:
  port: 8080
    #server.servlet.context-path=/KGD
    # setting spring WAS port to 8081 for handover port to vue server
  # setting and limit first path
# WAS Server Setting

