INSERT INTO test_item_list (name) values ('테스트용 아이템1');
INSERT INTO test_item_list (name) values ('테스트용 아이템2');
INSERT INTO test_item_list (name) values ('테스트용 아이템3');
INSERT INTO test_item_list (name) values ('테스트용 아이템4');
INSERT INTO test_item_list (name) values ('테스트용 아이템5');
INSERT INTO test_item_list (name) values ('테스트용 아이템6');
INSERT INTO test_item_list (name) values ('테스트용 아이템7');
INSERT INTO test_item_list (name) values ('테스트용 아이템8');
INSERT INTO test_item_list (name) values ('테스트용 아이템9');